---
- name: Fail if Linux kernel is less than version 3.10
  fail:
      msg="Docker requires version 3.10 or higher of the Linux kernel. \n
           Kernels older than 3.10 lack some of the features required to run Docker containers and contain known bugs which cause data loss and frequently panic under certain conditions."
  when: "{{ ansible_kernel | version_compare('3.10', '<=') }}"
  tags: docker

- name: For Ubuntu Precise, Docker requires the 3.13 kernel version.
  fail:
      msg="For Ubuntu Precise, Docker requires the 3.13 kernel version."
  when: "{{ ansible_kernel | version_compare('3.13', '<=') }} and {{ ansible_distribution_version == 12.04 }}"
  tags: docker

- name: Add Docker APT repository key
  apt_key:
    keyserver: "{{docker_apt_key_server}}"
    id: "{{docker_apt_key_id}}"
    state: present
  become: yes
  tags: docker

- name: Add Docker APT repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo ubuntu-{{ ansible_distribution_release }} main"
    filename: 'docker'
    state: present
  become: yes
  tags: docker

- name: For Ubuntu Trusty, Wily, and Xenial, install the linux-image-extra-* kernel packages, which allows you use the aufs storage driver.
  action: apt pkg="{{item}}" state=present update_cache=yes
  with_items:
    - "linux-image-extra-{{ ansible_kernel }}"
    - linux-image-extra-virtual
  when:
    - " {{ ansible_distribution_version == 16.04 or ansible_distribution_version == 15.10 or ansible_distribution_version == 14.04 }}"
    - docker_with_linux_image
  become: yes
  tags: docker

- name: For Ubuntu Precise, install the linux-image-generic-lts-trusty kernel, which allows you use the aufs storage driver.
  action: apt pkg="{{item}}" state=present update_cache=yes
  with_items:
    - linux-image-generic-lts-trusty
  when:
    - " {{ ansible_distribution_version == 12.04 }}"
    - docker_with_linux_image
  become: yes
  tags: docker

- name: Install Docker Engine
  apt: name={{item}} state=present update-cache=yes cache_valid_time=864000
  with_items:
    - docker-engine
  become: yes
  tags: docker

- name: Configure docker options
  lineinfile:
    dest: /etc/default/docker
    insertafter: ^#DOCKER_OPTS=.*
    regexp: ^DOCKER_OPTS=.*
    line: "DOCKER_OPTS=\"{{docker_opts}} \""
    state: present
  become: yes
  tags: docker
  notify:
    - docker restart

- shell: ip link show {{ansible_default_ipv4.interface}} | awk '/mtu/ { print $5}'
  when: docker_bridge_ip
  become: yes
  tags: docker
  register: mtu

- set_fact:
    docker_opts: "{{ docker_opts }} --bip={{docker_bridge_ip}}/24 --mtu {{mtu.stdout}}"
  when: docker_bridge_ip
  tags: docker

- shell: /sbin/lsmod | grep -c overlay
  register: isOverlay
  become: yes
  tags: docker

- set_fact:
    docker_opts: "{{ docker_opts }} --storage-driver=overlay2"
  when: isOverlay
  tags: docker

- set_fact:
    docker_opts: "{{ docker_opts }} --registry-mirror={{docker_mirror_protocol}}://{{docker_mirror_host}}:{{docker_mirror_port}}"
  when: docker_mirror_host
  tags: docker

- name: Configure docker options with upstart
  lineinfile:
    dest: /etc/default/docker
    insertafter: ^#DOCKER_OPTS=.*
    regexp: ^DOCKER_OPTS=.*
    line: "DOCKER_OPTS=\"{{docker_opts}}\""
    state: present
  when: "{{ ansible_distribution_version | version_compare('14.04', '<=') }}"
  become: yes
  tags: docker
  notify:
    - docker restart

- name: Create a directory for docker service systemd
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
    owner: root
    group: root
    mode: 0755
  when: "{{ ansible_distribution_version | version_compare('15.10', '>=') }}"
  become: true
  tags: docker

- name: Configure docker options with systemd
  template: src=docker.service.j2 dest=/etc/systemd/system/docker.service.d/docker.conf
  when: "{{ ansible_distribution_version | version_compare('15.10', '>=') }}"
  become: yes
  tags: docker
  notify:
    - docker restart

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-{{ ansible_system }}-{{ ansible_architecture }}"
    dest: /usr/local/bin/docker-compose
    mode: 0755
  become: yes
  tags: docker
